sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "8"

matrix:
  fast_finish: true

before_install:
  - npm install npm@5 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - ng test --code-coverage
  - ng build 

after_success:
  - codecov -t 02b6378e-c1ca-4c03-a2a5-1143a707d178